lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
plugins:
  - jekyll-relative-links
  - 
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# theme: jekyll-theme-architect
# theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: minima
# theme: jekyll-theme-minimal
theme: jekyll-theme-modernist
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine
